---
abstract: 'check if PAUSE permissions are consistent for all modules in a dist'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PAUSE-CheckPerms
requires:
  Moo: 0
  MooX::Options: 0
  PAUSE::Packages: 0.02
  PAUSE::Permissions: 0.06
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/App-PAUSE-CheckPerms
  repository: https://github.com/neilbowers/App-PAUSE-CheckPerms.git
version: 0.01
